build:
  image: iotapi322/ffmpeg-golang
  commands:
    - go get
    - go build
    - curl -L -o /tmp/big_buck_bunny_720p_2mb.mkv http://www.sample-videos.com/video/mkv/720/big_buck_bunny_720p_2mb.mkv
    - ./mkv2Appletv --help-long
    - ./mkv2Appletv -i /tmp/big_buck_bunny_720p_2mb.mkv show
    - ./mkv2Appletv -i /tmp/big_buck_bunny_720p_2mb.mkv suggest
    - ./mkv2Appletv -t -d -i /tmp/big_buck_bunny_720p_2mb.mkv convert


